/*
Auto-generated by: https://gltf.pmnd.rs/
*/

import React, { useRef, useEffect, useLayoutEffect } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'

export default function LogoEver({ tl, ...props }) {

    // Load the glTF model
    const logoEver = useGLTF('./logo-ever.glb')

    // Animate the logoEver using GSAP when the timeline (tl) is available
    useLayoutEffect(() => {
        if (tl) {
            // const theMaterial = logoEverRef.current.children[0].material;
            // console.log(logoEver.materials.Default);

            tl.from(logoEver.materials.Default, {
                opacity: 0,
                duration: 1.5,
                delay: 0.3,
            }, "-=0.3" );

            tl.from(logoEver.materials.Default, {
                emissiveIntensity: 0,
                duration: 2.5,
                delay: 0.3,
                ease: "elastic.out(4, 0.5)",
            }, "-=1.5" );
        }
    }, [tl]);

    useEffect(() => {
        logoEver.materials.Default.transparent = true;
        logoEver.materials.Default.emissiveIntensity = 2
    }, [])

    return (
        <primitive {...props} object={logoEver.scene} />
    )
}

useGLTF.preload('/logo-ever.glb')