/*
Auto-generated by: https://gltf.pmnd.rs/
*/

import React, { useRef, useEffect, useLayoutEffect } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { gsap } from 'gsap';

export default function Triangle({ tl, tlTwo, ...props }) {
    // Load the glTF model
    const logoTriangle = useGLTF('./logo-triangle.glb')
    const triangleRef = useRef()

    // Animate the triangle using GSAP when the timeline (tl) is available
    useLayoutEffect(() => {
        if (tl) {
            tl
                .from(triangleRef.current.scale, {
                    x: 0,
                    y: 0,
                    z: 0,
                    duration: 3.0,
                    ease: "power2.inOut",
                }, "-=0.3" )
                .from(triangleRef.current.position, {
                    z: -100,
                    duration: 3,
                    ease: "power2.inOut",
                    delay: 0.3,
                }, "-=3.3" )
                .from(triangleRef.current.rotation, {
                    y: Math.PI * 4,
                    x: Math.PI * 2,
                    duration: 3,
                    ease: "power2.inOut",
                    delay: 0.3,
                }, "-=3.0" );
        }
    }, [tl]);

    // Flash the triangle with a bright emissive color using the second timeline (tlTwo)
    useLayoutEffect(() => {
        if (tlTwo) {
            tlTwo
                .to(logoTriangle.materials.triangleMaterial, {
                    emissiveIntensity: 20,
                    duration: 0.25,
                    // ease: "power1.inOut",
                })
                .to(logoTriangle.materials.triangleMaterial, {
                    emissiveIntensity: 0.15,
                    duration: 0.25,
                    // ease: "power1.inOut",
                });
        }
    }, [tlTwo]);

    useEffect(() => {
        logoTriangle.materials.triangleMaterial.metalness = 0.3
        logoTriangle.materials.triangleMaterial.roughness = 0.25
        logoTriangle.materials.triangleMaterial.fog = false
        logoTriangle.materials.triangleMaterial.emissive = new THREE.Color(0x2f10c7)
        logoTriangle.materials.triangleMaterial.emissiveIntensity = 0.15
    }, [])

    return (
        <primitive ref={triangleRef} {...props} object={logoTriangle.scene} />
    )
}

useGLTF.preload('/logo-triangle.glb')